### ISSUE TITLE
[RPC] AccInputHash Problems

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#1002]
## Initial solution (implemented):
Call the s/c, If it returns 0x00....set it to 0x00 (otherwise you are returning a accInputHash for the wrong batchNum)
if it returns a non-zero hash, just set it

## Fix required:
Sync events SequenceBatches and from batch DB data you can compute all batches accInputHash and you store them in the DB.
When you save a batch in the DB during synchronization, also compute the accInputHash and store it.

**Comment by Sharonbc01** [comment]
Hey @revitteth is this done now.

**Comment by V-Staykov** [comment]
This is connected to this issue: https://github.com/0xPolygonHermez/cdk-erigon/issues/898

We've implemented a solution where we calculate the accInputHash upon request on the RPC in this PR:
https://github.com/0xPolygonHermez/cdk-erigon/pull/1161

I am closing the current issue, since it is kind of repeating the connected one.
