### ISSUE TITLE
Gas estimation can use 100% CPU and timeout

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1060]
A simple request to estimate gas seems like it can saturate the CPU and lead to an RPC timeout.

```bash
cast estimate --rpc-url http://127.0.0.1:33162 --create  0x5b5f56
```

This leads to a JSON RPC payload that looks like this:
```json
{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "eth_estimateGas",
    "params": [
        {
            "chainId": "0x2775",
            "data": "0x5b5f56",
            "from": "0x0000000000000000000000000000000000000000",
            "input": "0x5b5f56",
            "to": null
        },
        "latest"
    ]
}
```

![image](https://github.com/user-attachments/assets/dd61a048-dbf0-43f6-be80-128d041fdc63)

[profile002.pdf](https://github.com/user-attachments/files/16789843/profile002.pdf)

**Comment by V-Staykov** [comment]
This is expected and should happen on any EVM.

To estimate gas in EVM, we execute the transaction a bunch of times with a binary search. This transaction consumes unlimited amount of gas, so it always executes the maximum amount of times for the binary search, until it checks the upper gas limit.

The transaction takes unlimited gas, because it has a push0 and then a jmpdest, which returns to opcode 0 and this loops over and over again. Not much we can do here.

**Comment by hexoscott** [comment]
I agree, for an infinite loop this should be expected to time out
