### ISSUE TITLE
RPC errors on the zkevm RPC's

### ISSUE THREAD

**Issue by rahuldamodar94** [0xPolygon/cdk-erigon#1185]
We are running an indexer that queries the zkEVM public RPC to fetch some data from the blocks. 

These are the calls we make via web3.js library.

getBlock
getBlockNumber
getTransactionReceipt
getGasPrice

Seeing 3 types of errors.
1. NVALID json ""
2. Null receipt for some blocks
3. Failed to connect to RPC
4. Invalid Json Body.

Frequency - Would be 50-100+ in a week. Does work after retries though.

**Comment by hexoscott** [comment]
Hi @rahuldamodar94, a few questions:
- which endpoint are you calling?
- Are these requests being made server side or client side using web3 js?
- from the environment that the application is running from (if server side) can you use `cast` or a simple `curl` to make the same requests successfully?

The invalid JSON parts would indicate an HTML response is coming back, it would be useful to get a dump of the responses if possible

**Comment by py-zoid** [comment]
Hi @hexoscott ,

We are calling the following endpoints:
1. eth_getBlockByNumber
2. eth_getTransactionReceipt
3. eth_gasPrice

The calls are being made server-side. The RPC returns properly most of the time only occasionally it throws these errors and on subsequent retries we receive correctly again. So, I don't see a point in testing these calls with curl requests from the server. I'll try to see if we can get the response dump because these errors are being thrown by web3.js package on our app when it fails to decode the response.

**Comment by hexoscott** [comment]
Thank you for the details.  So an occasional failure might suggest hitting a rate limit somewhere in the pipeline and getting a 429 with an html body in the response.  How frequently are you making these calls?  It would be great if it's possible to get a dump of the response.

**Comment by py-zoid** [comment]
I don't think it's a rate limit error. After a few tests we observed that whenever we were receiving the `Invalid JSON RPC response: ""` error on our app our direct calls to the rpc are erroring out with `Request failed with status code 502`. This should narrow down the error scope.

**Comment by hexoscott** [comment]
Interesting, this is the first report we've had of this.  Which endpoint URL are you using?

**Comment by Sharonbc01** [comment]
Hi @py-zoid is this issue still valid? Can you share endpoint URL please. Thanks

**Comment by hexoscott** [comment]
Can this be closed now @py-zoid ?  There was a thread opened with Will about this and it looked to be related to cloudflare / load balancing?
