### ISSUE TITLE
`zkevm.sequencer-batch-seal-time` limits RPC update frequency

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1433]
I'm running `hermeznetwork/cdk-erigon:v2.60.0-beta6` and it seems like when I extend the `zkevm.sequencer-batch-seal-time` it also impacts the frequency of updates within the RPC.

To replicate, you can check out this branch https://github.com/0xPolygon/kurtosis-cdk/tree/jhilliard/f13-real-prover

Then fire up kurtosis
```
kurtosis run --enclave cdk --args-file .github/tests/combinations/fork13-new-cdk-stack-cdk-validium.yml .
```

I think the important element here is that this branch is configured for batches every 600s. It seems like if you query data from the sequencer's RPC, the data is only updated every 10 minutes even though from the logs, it's pretty clear that the blocks are being created:

![image](https://github.com/user-attachments/assets/331fd91f-5c35-4732-9441-3da68974611d)

In the screenshot above, `polycli monitor` is showing the delay in blocks. On the bottom, we can see the logs showing that block 33 and been mined, but the RPC call is showing that the tip of the chain is still at block 21.

**Comment by cffls** [comment]
I can confirm this happens only to sequencers. 
The "latest" block returned by the RPC endpoint corresponds to the block number stored in [`finish stage`](https://github.com/0xPolygonHermez/cdk-erigon/blob/zkevm/eth/stagedsync/stage_finish.go). 
When running under sequencer mode, a node will stay in block execution stage until the pending batch is closed either due to counter limit or batch seal timeout. As a result, the block number stored in finish stage won't be updated as frequently as L2 blocks are produced. 
When running in RPC mode, the node won't stick to execution stage. Instead, it will execute all new blocks received from datastream and go to the rest of stages immediately, including `finish stage`. Therefore, this issue doesn't happen to RPC nodes. 

The default stage looked up by the "latest" block RPC endpoint was `execution stage`. We decided to change it to `finish stage` as the indicator of latest block, because the state root of a block isn't calculated in `execution stage`, but the stage after. If we use `execution stage`, some RPCs endpoint, e.g. [zkevm_getProof](https://github.com/0xPolygonHermez/cdk-erigon/blob/3f888033477722adfd2d9426029787ae81adca0a/turbo/jsonrpc/zkevm_api.go#L1599), would fail. Unlike RPCs, the state root of a block and its block hash will be calculated in `execution stage`. 

With the finding of this issue, it seems reasonable to use different stages to infer the latest block for RPC endpoints:
* use `execution stage` for sequencers
* use `finish stage` for RPCs
