### ISSUE TITLE
[etrog] RPC Changes

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#38]
Etrog RPC changes:

- [ ] txHashL2 → eth_getTransactionReceiptL2
- [ ] return block info root where necessary

**Comment by kstoykov** [comment]
@revitteth @mandrigin @hexoscott 

#### Update eth_getTransactionByHash
This is not part of the issue's description but I checked the etrog document and it look like that we must also update eth_getTransactionByHash. Currently it searched only by eth-hash (keccac). It should support searching by zk-hash (poseidon). It is not decided yet whether it will be one method that searches by both hashes or two methods. I suggest to use the existing method and, if needed, we will introduce a new method when decided.

There is a structure stored in erigon db that is like a mapper between tx-hash and block number. This structure is used in eth_getTransactionByHash method to find the block number. After that, by having the block number, all transactions for that block are fetched. Then, there is a loop that compares each transaction's hash against the given one. During that search transactions' hashes (keccac) are computed on the fly.

In order to add support for search by both keccac and poseison hashes we can:
1. Update the mapper between tx-hash and block number. In addition to keccac-hash to block number, it will store poseidon-hash to block number.
2. Update the loop that compares hashes. In addition to comparing keccac hash, it will also compare poseison-hash. Both hashes will be computed on by fly.

Does this implementation plan looks good. Is there a better place in the code where I could put it?

#### Implement eth_getTransactionReceiptL2
There is a function eth_getTransactionReceipt that returns a transaction's receipt. It is an object with the following properties - <em>blockHash, blockNumber, transactionHash, transactionIndex, from, to, type, gasUsed, cumulativeGasUsed, contractAddress, logs, logsBloom, effectiveGasPrice, status, contractAddress.</em>

Initially I thought that we could modify eth_getTransactionReceiptL2 similar to eth_getTransactionByHash but after further reading, the etrog document states that eth_getTransactionReceiptL2 should return only - <em>status, cumulativeGasUsed and logs.</em>

Is this correct?

#### Include in block all information got from gRPC
There are two new fields that are coming from the streamer - L1BlockHash and L1InfoRoot. I checked the current RPC methods but I'm not 100% sure where exactly should these two new fields be added to. Maybe I'm on a completely wrong way?

**Comment by hexoscott** [comment]
If I understood a conversation correctly the other day, the new poseidon hashes aren't going to be used at the moment.  So just the keccak hash will be used.  I think this issue can be parked for now and brought back later.
