### ISSUE TITLE
Return Safe block info (eth_getBlockByNumber, eth_getTransactionByBlockNumberAndIndex, etc.)

### ISSUE THREAD

**Issue by andreclaro** [0xPolygon/cdk-erigon#388]
# Rationale
Currently, CDK-Erigon returns an error with message "Unknown block" when trying to get information about the `safe` block.

Example using the method `eth_getBlockByNumber`.
```
curl -s http://localhost:8545/ -X POST -H "Content-Type: application/json" --data '{"method":"eth_getBlockByNumber","params":["safe",false],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"error":{"code":-39001,"message":"Unknown block"}}
```

I also tried other methods like `eth_getTransactionByBlockNumberAndIndex` but I got the same result: "Unknown block":
```
curl http://localhost:8545 \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_getTransactionByBlockNumberAndIndex","params":["safe", "0x0"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"error":{"code":-39001,"message":"Unknown block"}}
```

The clients using the node requires access to both `finalized` and `safe` block information.

# Implementation
cdk-erigon should be able to return information about the safe block.

**Comment by mandrigin** [comment]
currently only `finalized` and `latest` are supported, we can potentially make `safe` the same as `finalized`, but not really sure what `safe` should really be.

**Comment by praetoriansentry** [comment]
My sense is, matching `finalized` would work. That's the behavior in the zkevm-node and cdk-validium-node (I think). 

https://github.com/0xPolygonHermez/zkevm-node/blob/2292cd529a202fab7867a96b7d3f54e5516c6e53/jsonrpc/types/codec.go#L201-L229

In both cases we're getting `GetLastVerifiedL2BlockNumberUntilL1Block`. The difference between the two seems to rely on the L1 commitment levels. So if a proof is submitted on L1, making a call with `safe` updates before `finalized` because we're using those values to determine the latest verified batch.

**Comment by mandrigin** [comment]
@praetoriansentry @andreclaro  thanks for the feedback, we fixed it and the fix is merged

**Comment by andreclaro** [comment]
Awesome! Thanks a million folks!
