### ISSUE TITLE
[Sequencer] batch with OOC was sequenced on the Integration Network 2

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#519]
```
executor batch 1027 response, ROM OOC, error: not enough arith counters to continue the execution
```

**Comment by krlosMata** [comment]
I was able to reproduce the execution of batch 1027 locally.
Digging into the real zk-counters computed, I realize that there is one top offender regarding the arithmetic zk-counters consumed.
The top offender is a `CALL` to address `0x07` --> `ecMul` precompiled

Therefore, I suspect that virtual counters are not correctly counted when `ecMul` precompiled is called.
Here is the implementation of precompiled zk-counters in our side:
- https://github.com/0xPolygonHermez/zkevm-commonjs/blob/develop/src/virtual-counters-manager.js#L287
- https://github.com/0xPolygonHermez/zkevm-commonjs/blob/develop/src/virtual-counters-manager.js#L296

Double check also the rest of the precompiled, since I'm not sure if this is a thing regarding the `ecMul` or it involves all the precompiled

**Comment by mandrigin** [comment]
@krlosMata can you check what virtual counters are you getting for this batch?

**Comment by krlosMata** [comment]
nop, I can get real counters spent:
```
"cnt_arithmetics": 234143,
  "cnt_binaries": 228993,
  "cnt_mem_aligns": 128,
  "cnt_keccak_hashes": 102,
  "cnt_poseidon_paddings": 546,
  "cnt_poseidon_hashes": 7571,
  "cnt_steps": 2144976,
```

**Comment by krlosMata** [comment]
After Erigon implemented the `zkevm_traceTransactionCounters` RPC endpoint, we can get a better view of the miscalculation on the zk-counters.

Therefore, those are the numbers regarding the `ecMul` precompile:
## REAL COUNTERS
```
"cnt_arith": 14657,
          "cnt_binary": 13816,
          "cnt_mem_align": 0,
          "cnt_keccak_f": 0,
          "cnt_padding_pg": 0,
          "cnt_poseidon_g": 0,
          "cnt_steps": 119520,
          "cnt_sha256_hashes": 0
```
## VIRTUAL
```
"counters": {
        "Steps": 630,
        "Binary": 42,
        "Arith": 4,
        "Poseidon": 336,
        "Padding": 2,
        "Sha": 0,
        "MemAlign": 0
      }
```
