### ISSUE TITLE
Upstream compatibility improvements

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#54]
From the initial fork/clone of erigon, there have been multiple changes which are making it difficult to rebase on the upstream.

We can refactor slightly to make upstream compatibility better:

- using `_zkevm.go` versions of files we have touched e.g. `blockchain.go` could potentially become `blockchain_zkevm.go` and have the changes ported there and the wire-up moved further up the call stack
- any other valid abstractions which allow the changes to be more easily made (perhaps undoing unecessary refactoring which may have occurred as part of the development process of the cdk-erigon node)

**Comment by LeoGuo621** [comment]
Here is https://github.com/0xPolygonHermez/cdk-erigon/pull/70 which has been successfully tested on hermez mainnet and testnet, and waiting for review.

**Comment by LeoGuo621** [comment]
Now there are still some conflicts unresolved. 
I've noted down the files with conflicts—totaling 84 in number, plz see 
[Files with conflicts.xlsx](https://github.com/0xPolygonHermez/cdk-erigon/files/14035731/Files.with.conflicts.xlsx)

1. In Sheet1, 30 files are due to significant code couplings, such as changes to function signatures or internal logic. 
2. In Sheet2, 54 files have conflicts due to differences in "imports" where "github.com/ledgerwatch/erigon-lib/chain" has been replaced with "github.com/ledgerwatch/erigon/chain"
