### ISSUE TITLE
[RPC] debug_traceBatchByNumber endpoint doesn't exist

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#564]
Should be same as traceBlockByNumber, but runs for txs from the batch.

Example request
```
{
	"jsonrpc":"2.0",
	"method":"debug_traceBatchByNumber",
	"params":["0x1",{"tracer": "callTracer"}],
	"id":83
}
```

Example expected response
```

{
    "jsonrpc": "2.0",
    "id": 83,
    "result": [
        {
            "txHash": "0x7adde93707c0628ec6c516468f8d13f9efaf7f0c7ffeddbbdfbfef9e8c82f48b",
            "result": {
                "from": "0x273c0c1382b73c161e315ea700ec73ecb0348238",
                "gas": "0x1c9c380",
                "gasUsed": "0x18c8c",
                "to": "0xfe12abaa190ef0c8638ee0ba9f828bf41368ca0e",
                "input": "0xf811bff7000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a40d5f56745a118d0906a34e69aec8c0db1cb8fa000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000000",
                "calls": [
                    {
                        "from": "0xfe12abaa190ef0c8638ee0ba9f828bf41368ca0e",
                        "gas": "0x1c22b36",
                        "gasUsed": "0x1195f",
                        "to": "0x608484d3e94fc775e3dcb06b0b48486c60a315e6",
                        "input": "0xf811bff7000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a40d5f56745a118d0906a34e69aec8c0db1cb8fa000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000000",
                        "value": "0x0",
                        "type": "DELEGATECALL"
                    }
                ],
                "value": "0x0",
                "type": "CALL"
            }
        }
    ]
}
```

**Comment by Sharonbc01** [comment]
tagging @tclemos

**Comment by Sharonbc01** [comment]
Hi @mandrigin  yesterday @eduadiez confirmed this RPC method is not supported on Etherscan and you confirmed it is not supported on Block explorer so can this issue be close?

**Comment by mandrigin** [comment]
I think it is nice to have it here, but I will remove milestones from it, to just put it to an abstract “backlog” :)

**Comment by tclemos** [comment]
Just to add more context, this endpoint was created prior to Etrog because the network used to have a single TX per block. It was meant to help trace multiple transactions in a single request to the RPC.

**Comment by mandrigin** [comment]
Ah, okay, so maybe we don’t need it? We have debug_traceBlockByNumber? @tclemos close this one if you agree

**Comment by tclemos** [comment]
Edu is the best person to make this decision; please check it with him.

IMO, the network has transactions and blocks, but in the end, the network operates in Batches. 
This endpoint allows us to understand the whole batch execution in detail without having to map each batch manually, figure out all the blocks within this batch, request all the block traces individually, and pack them together.

Currently, the Executor only allows a single transaction to be traced during the batch execution; in other words, when tracing a batch or a block by number, we have to call the executor separately for each transaction, executing all the previous transactions + the transaction we want to trace, for example:

```
Scenario
- Request the trace of a block with four transactions

Execution:
- RPC detects the trace block by number request
- RPC loads all the TX hashes in this block
- Executes the transaction with index 0 and stores the trace of TX with index 0 
- Executes the transaction with indexes 0 and 1 and stores the trace of TX with index 1
- Executes the transaction with indexes 0, 1, and 2 and stores the trace of TX with index 2
- Executes the transaction with indexes 0, 1, 2, and 3 and stores the trace of TX with index 3
- Group all the traces in a single RPC response and return
```

I don't know precisely how Erigon works in this case and how it integrates with the executor, but as you can see in the explanation, the current implementation wastes a lot of execution resources by re-executing all the previous transactions. This is necessary because the Executor doesn't store the intermediate states for each transaction, so the intermediate state needs to be recreated every time.

It would be interesting to make sure the `debug_traceBlockByNumber`, `debug_traceBlockByHash`, and `debug_traceBatchByNumber` had a way to avoid reprocessing all the previous transactions to save resources and be performant.

**Comment by eduadiez** [comment]
If I remember correctly I think we made this endpoint with the idea that etherescan would use it since going block by block was too slow for them and it had become a bottleneck, but they seem to have found another way to do it.
Right now I think this would be a good to have, but I don't have a use case in mind where it is strictly necessary.
