### ISSUE TITLE
OldAccInputHash for lower forkids

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#898]
The contract ABI is different for lower forkids, so calling to get oldAccInputHash from the L1 for lower forkids fails. This needs a little investigation and an implementation to fix.

Currently getBatchByNumber is returning the oldAccInputHash as 0x00...0 when retries are exceeded and this fails, which needs a proper fix.

**Comment by V-Staykov** [comment]
Turns out this will be a bit more work. First of all from the contract we only get the last batch in the sequence accInputHash. For any other batch we need to calculate it and we don't.

Here is the algorithm to calculate it according to Carlos:
```

each batch has a different accInputHash (since it depends on its data and on the previousAccInputHash)
how to compute intermediateAccInjputHashes?
you can get the very first hash of the sequence (ex: from 4 to 10)
you got batch_4_accInputHash & batch_10_accInputHash
you detect event:
/**
     * @dev Emitted when the trusted sequencer sends a new batch of transactions
     */
    event SequenceBatches(uint64 indexed numBatch, bytes32 l1InfoRoot);
you get the calldata: all batches data, l2Coinabse, maxSequencetimestamp
you get event data: l1InfoRoot
you can build all the intermediate accInputHahes from batch 4 to 10
you can do a sanity check that batch 10 computed batches the one on-chain
```

here is the js implementation for the above:
https://github.com/0xPolygonHermez/zkevm-commonjs/blob/main/src/contract-utils.js#L15
